var getTerapiaIntensiva = function() {
return [
    {
        "denominazione_regione": "Sardegna",
        "30%": "65",
        "numero_soglia": "59",
        "posti_rimasti": "59",
        "saturazione": "2,777777778",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "216",
        "terapia_intensiva": "6"
    },
    {
        "denominazione_regione": "Sicilia",
        "30%": "254",
        "numero_soglia": "211",
        "posti_rimasti": "211",
        "saturazione": "5,088757396",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "845",
        "terapia_intensiva": "43"
    },
    {
        "denominazione_regione": "Calabria",
        "30%": "47",
        "numero_soglia": "39",
        "posti_rimasti": "39",
        "saturazione": "5,128205128",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "156",
        "terapia_intensiva": "8"
    },
    {
        "denominazione_regione": "Basilicata",
        "30%": "26",
        "numero_soglia": "26",
        "posti_rimasti": "26",
        "saturazione": "0",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "88",
        "terapia_intensiva": "0"
    },
    {
        "denominazione_regione": "Puglia",
        "30%": "176",
        "numero_soglia": "157",
        "posti_rimasti": "157",
        "saturazione": "3,242320819",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "586",
        "terapia_intensiva": "19"
    },
    {
        "denominazione_regione": "Campania",
        "30%": "186",
        "numero_soglia": "169",
        "posti_rimasti": "169",
        "saturazione": "2,741935484",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "620",
        "terapia_intensiva": "17"
    },
    {
        "denominazione_regione": "Molise",
        "30%": "12",
        "numero_soglia": "11",
        "posti_rimasti": "11",
        "saturazione": "2,564102564",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "39",
        "terapia_intensiva": "1"
    },
    {
        "denominazione_regione": "Abruzzo",
        "30%": "56",
        "numero_soglia": "49",
        "posti_rimasti": "49",
        "saturazione": "3,783783784",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "185",
        "terapia_intensiva": "7"
    },
    {
        "denominazione_regione": "Lazio",
        "30%": "283",
        "numero_soglia": "224",
        "posti_rimasti": "224",
        "saturazione": "6,256627784",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "943",
        "terapia_intensiva": "59"
    },
    {
        "denominazione_regione": "Umbria",
        "30%": "35",
        "numero_soglia": "28",
        "posti_rimasti": "28",
        "saturazione": "6,034482759",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "116",
        "terapia_intensiva": "7"
    },
    {
        "denominazione_regione": "Marche",
        "30%": "63",
        "numero_soglia": "40",
        "posti_rimasti": "40",
        "saturazione": "10,952380952",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "210",
        "terapia_intensiva": "23"
    },
    {
        "denominazione_regione": "Toscana",
        "30%": "181",
        "numero_soglia": "155",
        "posti_rimasti": "155",
        "saturazione": "4,318936877",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "602",
        "terapia_intensiva": "26"
    },
    {
        "denominazione_regione": "Emilia Romagna",
        "30%": "228",
        "numero_soglia": "192",
        "posti_rimasti": "192",
        "saturazione": "4,736842105",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "760",
        "terapia_intensiva": "36"
    },
    {
        "denominazione_regione": "Liguria",
        "30%": "68",
        "numero_soglia": "59",
        "posti_rimasti": "59",
        "saturazione": "3,982300885",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "226",
        "terapia_intensiva": "9"
    },
    {
        "denominazione_regione": "Friuli Venezia Giulia",
        "30%": "53",
        "numero_soglia": "36",
        "posti_rimasti": "36",
        "saturazione": "9,714285714",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "175",
        "terapia_intensiva": "17"
    },
    {
        "denominazione_regione": "Veneto",
        "30%": "300",
        "numero_soglia": "259",
        "posti_rimasti": "259",
        "saturazione": "4,1",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "1000",
        "terapia_intensiva": "41"
    },
    {
        "denominazione_regione": "Trento",
        "30%": "27",
        "numero_soglia": "25",
        "posti_rimasti": "25",
        "saturazione": "2,222222222",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "90",
        "terapia_intensiva": "2"
    },
    {
        "denominazione_regione": "Bolzano",
        "30%": "30",
        "numero_soglia": "27",
        "posti_rimasti": "27",
        "saturazione": "3",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "100",
        "terapia_intensiva": "3"
    },
    {
        "denominazione_regione": "Lombardia",
        "30%": "425",
        "numero_soglia": "378",
        "posti_rimasti": "378",
        "saturazione": "3,319209040",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "1416",
        "terapia_intensiva": "47"
    },
    {
        "denominazione_regione": "Valle d'Aosta",
        "30%": "9",
        "numero_soglia": "9",
        "posti_rimasti": "9",
        "saturazione": "0",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "30",
        "terapia_intensiva": "0"
    },
    {
        "denominazione_regione": "Piemonte",
        "30%": "188",
        "numero_soglia": "167",
        "posti_rimasti": "167",
        "saturazione": "3,343949045",
        "spiegone": "Mancano <AGG(Posti rimasti)> prima che il sistema vada in sofferenza",
        "stringa_soglia": "dalla",
        "data_aggiornamento": "07/01/2021",
        "data": "2021-11-06T17:00:00",
        "fonte": "Agenas",
        "info_from": "Agenas",
        "update": "11/05/2021",
        "posti_totali_ti": "628",
        "terapia_intensiva": "21"
    }
]}