name: update_terapia_intensiva

on:
  #   TEMPORARILY DISABLED FOR TESTING PURPOSES
  # schedule:
  # - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2 # checkout the repository content to github runner.
     - uses: actions/setup-python@v2
       with:
         python-version: 3.6 #install the python needed
     - name: Setup dependencies
       run: |
         python -m pip install --upgrade pip
         pip install requests selenium
     - run: |
         python update_terapia_intensiva.py
     - name: Commit and push file
       run: |
         git config --global user.name "Davide Zago"
         git config --global user.email "***REMOVED***"
         git add terapia_intensiva.js
         git commit -m "Daily update of data: 'terapia intensiva'"
         git push
