name: update_terapia_intensiva

on:
  schedule:
  - cron: '0 19 * * *'  # update at 19:00
  workflow_dispatch:  # run manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2  # checkout the repository content to github runner.
     - uses: actions/setup-python@v2
       with:
         python-version: 3.6 # install the python needed
     - name: Setup dependencies
       run: |
         python -m pip install --upgrade pip
         pip install requests selenium
     - run: |
         python update_terapia_intensiva.py
     - name: Commit and push file
       run: |
         if ! git diff-index --quiet HEAD --; then
           git config --global user.name "Davide Zago"
           git config --global user.email ""
           git add terapia_intensiva.js
           git commit -m "Daily update of 'terapia intensiva.js'"
           git push
         fi
